M_PopUp_nombre="M+ Los 2000"
M_PopUp_logo="https://raw.githubusercontent.com/davidmuma/picons_dobleM/master/icon/M%2B%20Los%202000.png"

M_PopUp2_nombre="M+ PopUp 2"
M_PopUp2_logo="https://raw.githubusercontent.com/davidmuma/picons_dobleM/master/icon/M%2B%20PopUp%202.png"